/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface AutonomifyExecutorInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "agentNonce"
      | "computeNextNullifier"
      | "execute"
      | "executeWithNullifier"
      | "getNonce"
      | "isNullifierUsed"
      | "usedNullifiers"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "Executed"): EventFragment;

  encodeFunctionData(
    functionFragment: "agentNonce",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "computeNextNullifier",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "execute",
    values: [BytesLike, AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "executeWithNullifier",
    values: [BytesLike, AddressLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "getNonce", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "isNullifierUsed",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "usedNullifiers",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "agentNonce", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "computeNextNullifier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "execute", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "executeWithNullifier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getNonce", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isNullifierUsed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "usedNullifiers",
    data: BytesLike
  ): Result;
}

export namespace ExecutedEvent {
  export type InputTuple = [
    agentId: BytesLike,
    target: AddressLike,
    selector: BytesLike,
    nullifier: BytesLike,
    success: boolean,
    returnData: BytesLike
  ];
  export type OutputTuple = [
    agentId: string,
    target: string,
    selector: string,
    nullifier: string,
    success: boolean,
    returnData: string
  ];
  export interface OutputObject {
    agentId: string;
    target: string;
    selector: string;
    nullifier: string;
    success: boolean;
    returnData: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AutonomifyExecutor extends BaseContract {
  connect(runner?: ContractRunner | null): AutonomifyExecutor;
  waitForDeployment(): Promise<this>;

  interface: AutonomifyExecutorInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  agentNonce: TypedContractMethod<[arg0: BytesLike], [bigint], "view">;

  computeNextNullifier: TypedContractMethod<
    [agentId: BytesLike],
    [string],
    "view"
  >;

  execute: TypedContractMethod<
    [agentId: BytesLike, target: AddressLike, data: BytesLike],
    [[boolean, string] & { success: boolean; result: string }],
    "payable"
  >;

  executeWithNullifier: TypedContractMethod<
    [
      agentId: BytesLike,
      target: AddressLike,
      data: BytesLike,
      customNullifier: BytesLike
    ],
    [[boolean, string] & { success: boolean; result: string }],
    "payable"
  >;

  getNonce: TypedContractMethod<[agentId: BytesLike], [bigint], "view">;

  isNullifierUsed: TypedContractMethod<
    [nullifier: BytesLike],
    [boolean],
    "view"
  >;

  usedNullifiers: TypedContractMethod<[arg0: BytesLike], [boolean], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "agentNonce"
  ): TypedContractMethod<[arg0: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "computeNextNullifier"
  ): TypedContractMethod<[agentId: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "execute"
  ): TypedContractMethod<
    [agentId: BytesLike, target: AddressLike, data: BytesLike],
    [[boolean, string] & { success: boolean; result: string }],
    "payable"
  >;
  getFunction(
    nameOrSignature: "executeWithNullifier"
  ): TypedContractMethod<
    [
      agentId: BytesLike,
      target: AddressLike,
      data: BytesLike,
      customNullifier: BytesLike
    ],
    [[boolean, string] & { success: boolean; result: string }],
    "payable"
  >;
  getFunction(
    nameOrSignature: "getNonce"
  ): TypedContractMethod<[agentId: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "isNullifierUsed"
  ): TypedContractMethod<[nullifier: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "usedNullifiers"
  ): TypedContractMethod<[arg0: BytesLike], [boolean], "view">;

  getEvent(
    key: "Executed"
  ): TypedContractEvent<
    ExecutedEvent.InputTuple,
    ExecutedEvent.OutputTuple,
    ExecutedEvent.OutputObject
  >;

  filters: {
    "Executed(bytes32,address,bytes4,bytes32,bool,bytes)": TypedContractEvent<
      ExecutedEvent.InputTuple,
      ExecutedEvent.OutputTuple,
      ExecutedEvent.OutputObject
    >;
    Executed: TypedContractEvent<
      ExecutedEvent.InputTuple,
      ExecutedEvent.OutputTuple,
      ExecutedEvent.OutputObject
    >;
  };
}
